# Load in NumPy (remember to pip install numpy first)

In [103]:
import numpy as np

# The Basics

In [104]:
a = np.array([1,2,3],dtype="int32")
print(a)

[1 2 3]


In [105]:
b = np.array([[5.0,6.0,7.0,8.0],[6.0,7.0,8.0,9.0]])
print(b)

[[5. 6. 7. 8.]
 [6. 7. 8. 9.]]


In [106]:
#Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [107]:
#Get shape
print(a.shape)
print(b.shape)

(3,)
(2, 4)


In [108]:
#Get Type
print(a.dtype)
print(b.dtype)

int32
float64


In [109]:
#Get each item size
print(a.itemsize)
print(b.itemsize)

4
8


In [110]:
#Get No of element
print(a.size)
print(b.size)

3
8


In [111]:
#Get total size
print(a.size * a.itemsize)
print(b.size * b.itemsize)

#Or
print(a.nbytes)
print(b.nbytes)

12
64
12
64


# Accessing/Changing specific elements, rows, columns, etc

In [112]:
c = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [113]:
#Get a specific element [r, c]
print(c[0,-1])
print(c[1,3])

7
11


In [114]:
#Get a specific row
c[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [115]:
#Get a specific column
c[: ,0]

array([1, 8])

In [116]:
#Getting a little more fancy [startindex: endindex: stepsize]
print(c[0, 1:6:2])
print(c[0, :-1:2])

[2 4 6]
[1 3 5]


In [117]:
#Changing element
c[1,-1] = 0
print(c)

c[:,2] = 5
print(c)

c[:,2] = [20,30]
print(c)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13  0]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13  0]]
[[ 1  2 20  4  5  6  7]
 [ 8  9 30 11 12 13  0]]


# 3d example

In [118]:
d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [119]:
#Getting specific element (work outside in)
print(d[0,1,1])
print(d[:,1,:])

4
[[3 4]
 [7 8]]


In [120]:
#replace
d[:,1,:]=[[9,9],[8,8]]
print(d)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


# Initializing Different types of Arrays

In [121]:
# All 0s matrix
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [122]:
# All 1s matrix
np.ones((5,5),dtype='int32')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [123]:
# Any other number (dtype is optional for all array)
np.full((2,2),100,dtype='float32')

array([[100., 100.],
       [100., 100.]], dtype=float32)

In [124]:
# Any other number (full_like)
print(np.full_like(b,10))
print(np.full(b.shape,10))

[[10. 10. 10. 10.]
 [10. 10. 10. 10.]]
[[10 10 10 10]
 [10 10 10 10]]


In [125]:
# Random decimal numbers
print(np.random.rand(4,2))
print()
print(np.random.random_sample(b.shape))

[[0.94894502 0.62725906]
 [0.05580207 0.03300274]
 [0.27494368 0.09951648]
 [0.67638113 0.91160051]]

[[0.08039423 0.4287023  0.68693445 0.51017298]
 [0.58139337 0.15131583 0.30425428 0.2166247 ]]


In [126]:
# Random Integer values
print(np.random.randint(7,size=(3,3)))
print(np.random.randint(-9,7,size=(3,3)))

[[2 5 4]
 [5 3 1]
 [1 6 0]]
[[-6  6  3]
 [-8  2 -9]
 [ 2 -3 -2]]


In [127]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [128]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [129]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1]=9
print(z)

output[1:4 ,1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


## Be careful when copying arrays !!! 

In [130]:
a = np.array([1,2,3])
b = a  # if we change b and also reflect in a so we use copy
b = a.copy()
b[0] = 100

print(a)
print(b)


[1 2 3]
[100   2   3]


### Mathematics

In [131]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [132]:
a+2

array([3, 4, 5, 6])

In [133]:
a-2

array([-1,  0,  1,  2])

In [134]:
print(a)

[1 2 3 4]


In [135]:
a*2

array([2, 4, 6, 8])

In [136]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [137]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [138]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [139]:
# take sin cos and tan
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
[ 1.55740772 -2.18503986 -0.14254654  1.15782128]


### Linear Algebra

In [140]:
# Matrix multiplication
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [141]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### Statistics

In [142]:
stats = np.array([[4,2,3,1],[5,6,7,8]])
stats

array([[4, 2, 3, 1],
       [5, 6, 7, 8]])

In [143]:
#Find minimum value
print(np.min(stats, axis=0))  # axis represents ????
print(np.min(stats))

[4 2 3 1]
1


In [144]:
#Find maximum value
print(np.max(stats))
print(np.max(stats, axis=1))

8
[4 8]


In [145]:
# sum of all element in matrix
print(np.sum(stats))
print(np.sum(stats,axis=1))

36
[10 26]


### Reorganizing Arrays

In [146]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [147]:
# Vertically stacking vectors when size is mismatch throws error
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

print(np.vstack([v1,v2]))
print(np.vstack([v1,v2,v2,v1]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]
 [1 2 3 4]]


In [148]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

print(np.hstack([h1,h2]))

[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


### Miscellaneous

#### Load Data from File

In [162]:
filedata = np.genfromtxt('data.txt',delimiter=',')
print(filedata)
print(filedata.astype('int32'))
filedata = filedata.astype('int32')

[[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 19.]
 [20. 21. 22. 23. 24. 25. 26. 27. 28.]]
[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 19]
 [20 21 22 23 24 25 26 27 28]]


#### Boolean Masking and Advanced Indexing

In [164]:
filedata>5

array([[False, False, False, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [165]:
filedata[filedata>5]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 19, 20, 21, 22, 23,
       24, 25, 26, 27, 28])

In [166]:
# You can index with a list in NUMPY
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [167]:
np.any(filedata > 5, axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

In [168]:
((filedata > 10)&(filedata < 20))

array([[False, False, False, False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False]])